var sampleGroup1 = [
  { name: "majestate-ninja", label: "majestate ninja",
    volume: 0.4, keyLabel: "Q", keyBinding: 113 },
  { name: "ninja-majestate", label: "ninja majestate",
    volume: 0.4, keyLabel: "W", keyBinding: 119 },
  { name: "nu-pot-sa-inot", label: "nu pot să inot la apă",
    volume: 0.4, keyLabel: "E", keyBinding: 101 },
  { name: "brebex", label: "brebex",
    volume: 2.5, keyLabel: "R", keyBinding: 114, spacer: 1 },
  { name: "elemelix", label: "elemelix",
    volume: 2.4, keyLabel: "T", keyBinding: 116, spacer: 1 },
  { name: "taliana", label: "taliană",
    volume: 2.4, keyLabel: "Y", keyBinding: 121, spacer: 1 },
  { name: "republistica-interumana", label: "republistica interumană",
    volume: 1.6, keyLabel: "A", keyBinding: 97 },
  { name: "omul-invizibil", label: "omul invizibil",
    keyLabel: "S", volume: 1.8, keyBinding: 115, spacer: 1 },
  { name: "infrarosu", label: "infraroșu",
    volume: 1.6, keyLabel: "D", keyBinding: 100, spacer: 1 },
  { name: "unda-prin-zid", label: "unda prin zid",
    volume: 2, keyLabel: "F", keyBinding: 102, spacer: 1 },
  { name: "laba", label: "laba",
    volume: 10, keyLabel: "G", keyBinding: 103, spacer: 1 },
  { name: "mos-craciun", label: "moș crăciun",
    volume: 0.6, keyLabel: "H", keyBinding: 104, spacer: 1 },
  { name: "simt-mesajul-muzicii", label: "simt mesajul muzicii",
    volume: 1, keyLabel: "Z", keyBinding: 122 },
  { name: "americanii-nu-se-baga", label: "americanii nu se bagă",
    volume: 1.8, keyLabel: "X", keyBinding: 120 },
  { name: "un-fel-de-schen", label: "un fel de schen",
    volume: 2.4, keyLabel: "C", keyBinding: 99 },
  { name: "am-facut-o-scoala", label: "am facut o școală",
    volume: 3, keyLabel: "V", keyBinding: 118 },
  { name: "vorbesti-cu-mine", label: "vorbești cu mine",
    volume: 1.6, keyLabel: "B", keyBinding: 98 },
  { name: "tre-sa-iau-un-pietroi", label: "tre să iau un pietroi",
    volume: 1.5, keyLabel: "N", keyBinding: 110 }
]

sampleGroup2 = [
  { name: "indragostita-sau-drogata", label: "îndrăgostită sau drogată",
    volume: 2.2, keyLabel: "Q", keyBinding: 113 },
  { name: "empty-button-W", label: "",
    volume: 0.4, keyLabel: "W", keyBinding: 119, spacer: 2 },
  { name: "empty-button-E", label: "",
    volume: 0.4, keyLabel: "E", keyBinding: 101, spacer: 2 },
  { name: "empty-button-R", volume: 2.5, label: "",
    keyLabel: "R", keyBinding: 114, spacer: 2 },
  { name: "empty-button-T", label: "",
    volume: 2.4, keyLabel: "T", keyBinding: 116, spacer: 2 },
  { name: "empty-button-Y", label: "",
    volume: 2.4, keyLabel: "Y", keyBinding: 121, spacer: 2 },
  { name: "empty-button-A", label: "",
    volume: 1.6, keyLabel: "A", keyBinding: 97, spacer: 2 },
  { name: "empty-button-S", label: "",
    volume: 1.8, keyLabel: "S", keyBinding: 115, spacer: 2 },
  { name: "empty-button-D", label: "",
    volume: 1.6, keyLabel: "D", keyBinding: 100, spacer: 2 },
  { name: "empty-button-F", label: "",
    volume: 2, keyLabel: "F", keyBinding: 102, spacer: 2 },
  { name: "empty-button-G", label: "",
    volume: 10, keyLabel: "G", keyBinding: 103, spacer: 2 },
  { name: "empty-button-H", label: "",
    volume: 0.6, keyLabel: "H", keyBinding: 104, spacer: 2 },
  { name: "empty-button-Z", label: "",
    volume: 1, keyLabel: "Z", keyBinding: 122, spacer: 2 },
  { name: "empty-button-X", label: "",
    volume: 1.8, keyLabel: "X", keyBinding: 120, spacer: 2 },
  { name: "empty-button-C", label: "",
    volume: 2.4, keyLabel: "C", keyBinding: 99, spacer: 2 },
  { name: "empty-button-V", label: "",
    keyLabel: "V", volume: 3, keyBinding: 118, spacer: 2 },
  { name: "empty-button-B", label: "",
    keyLabel: "B", volume: 1.6, keyBinding: 98, spacer: 2 },
  { name: "empty-button-N", label: "",
    keyLabel: "N", volume: 1.5, keyBinding: 110, spacer: 2 }
]

sampleGroupIds = {
  "group-1": sampleGroup1,
  "group-2": sampleGroup2
}

